DOCKER_IMAGE="github-api-front:latest"
DOCKER_CONTAINER="github-api-front_dev"

LOCAL_PATH=$(pwd)
VIRTUAL_PATH="/home"
VOLUME="$LOCAL_PATH:$VIRTUAL_PATH"

NEXT_JS_LOCAL_PORT=3000
NEXT_JS_VIRTUAL_PORT=3000
NEXT_JS_PORT="$NEXT_JS_LOCAL_PORT:$NEXT_JS_VIRTUAL_PORT"

STORY_BOOKS_LOCAL_PORT=6006
STORY_BOOKS_VIRTUAL_PORT=6006
STORY_BOOKS_PORT="$STORY_BOOKS_LOCAL_PORT:$STORY_BOOKS_VIRTUAL_PORT"

CMD="/bin/bash"

docker pull ubuntu:latest
docker build --tag=$DOCKER_IMAGE .
docker container run --rm -it --name $DOCKER_CONTAINER -w $VIRTUAL_PATH -v $VOLUME -p $NEXT_JS_PORT -p $STORY_BOOKS_PORT $DOCKER_IMAGE $CMD